apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: iTunes
  description: |
    xyz is an open-source developer portal that puts the developer experience first.
  labels:
    backstage.io/custom: custom_label_value
  links:
    - title: Website
      url: http://backstage.io
    - title: Documentation
      url: https://backstage.io/docs
    - title: Storybook
      url: https://backstage.io/storybook
    - title: Discord Chat
      url: https://discord.com/invite/EBHEGzX
  annotations:
    github.com/project-slug: nileshfarkade/itunes
    lighthouse.com/website-url: https://backstage.io
spec:
  type: library
  owner: Nilesh
  lifecycle: experimental
  system: public-websites
  profile:
    email: jenny-doe@example.com
    picture: https://example.com/staff/jenny-with-party-hat.jpeg
  memberOf: [team-b, employees]
tags:
  - changelog
